module Helpers (..) where

import Json.Encode exposing (string)
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.CssHelpers exposing (..)
import Model exposing (..)


body title content =
  article
    [ class "content wrap" ]
    [ h2
        [ class "post-title" ]
        [ text title ]
    , div
        [ class "post text" ]
        [ content ]
    ]


head =
  header
    []
    [ stylesheetLink "/style.css"
    , stylesheetLink "http://fonts.googleapis.com/css?family=Gentium+Book+Basic"
    , Html.node "script" [ attribute "src" "/Native/Highlight.js" ] []
    , stylesheetLink "/default.css"
    , a
        []
        [ img
            [ src "/logo.png"
            , class "logo"
            ]
            []
        ]
    , a
        []
        [ h1 [] [ text "Tech" ]
        ]
    ]


authorView : Author -> Html
authorView author =
  div
    [ class "content wrap" ]
    [ img [ src author.img ] []
    , br [] []
    , strong [] [ text author.fullName ]
    , br [] []
    , a [ href ("https://twitter.com" ++ author.twitter) ] [ text ("@" ++ author.twitter) ]
    , br [] []
    , text "Engineer at "
    , a [ href "http://noredink.com" ] [ text "NoRedInk" ]
    ]


foot : Html
foot =
  footer
    [ class "wrap" ]
    [ licenseView ]


{-| Renders license copy generated by https://creativecommons.org/choose/
-}
licenseView : Html
licenseView =
  div
    [ class "license" ]
    [ a
        [ rel "license"
        , href "http://creativecommons.org/licenses/by/4.0/"
        ]
        [ img
            [ alt "Creative Commons License"
            , Html.Attributes.style [ ( "border-width", "0" ) ]
            , src "https://i.creativecommons.org/l/by/4.0/88x31.png"
            ]
            []
        ]
    , br [] []
    , text "This work by "
    , a
        [ property "xmlns:cc" (string "http://creativecommons.org/ns#")
        , href "https://www.noredink.com"
        , property "property" (string "cc:attributionName")
        , rel "cc:attributionURL"
        ]
        [ text "NoRedInk" ]
    , text " is licensed under a "
    , a
        [ rel "license"
        , href "http://creativecommons.org/licenses/by/4.0/"
        ]
        [ text "Creative Commons Attribution 4.0 International License" ]
    , text "."
    ]


createView author title content =
  div
    []
    [ head
    , body title content
    , authorView author
    , foot
    ]
